server:
  port: 9090

spring:
  database:
    name: fs
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/${spring.database.name}?rewriteBatchedStatements=true&allowMultiQueries=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          # 最大连接数(使用负值表示没有限制) 默认为 8
          max-active: 10
          # 最大阻塞等待时间(使用负值表示没有限制) 默认为 -1 ms
          max-wait: -1
          # 最大空闲连接 默认为 8
          max-idle: 5
          # 最小空闲连接 默认为 0
          min-idle: 0


logging:
  level:
    root: info

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  production: false
